name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (optional for tests)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python --version

      - name: Build Docker image
        run: |
          docker build -t notely:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ secrets.GCP_SERVICE_ACCOUNT != '' }}   # Guard: nur deployen, wenn Creds vorhanden
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      # Optional: Docker auth für Artifact Registry (falls pushen nötig ist)
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev -q

      # Beispiel: wir deployen die LATEST-Version aus Artifact Registry
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --max-instances=4
